//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSP_Rwanda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Developer
    {
        public int DeveloperID { get; set; }
        public string DeveloperFName { get; set; }
        public string DeveloperLName { get; set; }
        public string PreferredLanguage { get; set; }
        public string ProfilePic { get; set; }
    }
}
