//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSP_Rwanda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expert
    {
        public int ExpertsID { get; set; }
        public string ExpertFName { get; set; }
        public string ExpertLName { get; set; }
        public string Specialization { get; set; }
        public string Country { get; set; }
        public string ProfilePic { get; set; }
    }
}
