//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSP_Rwanda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string StudentFName { get; set; }
        public string StudentLName { get; set; }
        public string ContactNumber { get; set; }
        public string EmailID { get; set; }
        public string ProfilePic { get; set; }
    }
}
