//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSP_Rwanda
{
    using System;
    using System.Collections.Generic;
    
    public partial class University
    {
        public int UniversityID { get; set; }
        public string UniversityName { get; set; }
        public string Logo { get; set; }
    }
}
